// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package nginx

import (
	"omp/api/nginx"
)

type ControllerV1 struct{}

func NewV1() nginx.INginxV1 {
	return &ControllerV1{}
}
