// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"omp/internal/dao/internal"
)

// nginxSwitchStatusDao is the data access object for the table nginx_switch_status.
// You can define custom methods on it to extend its functionality as needed.
type nginxSwitchStatusDao struct {
	*internal.NginxSwitchStatusDao
}

var (
	// NginxSwitchStatus is a globally accessible object for table nginx_switch_status operations.
	NginxSwitchStatus = nginxSwitchStatusDao{internal.NewNginxSwitchStatusDao()}
)

// Add your custom methods and functionality below.
